version: "3.6"

services:
  flood-db:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      PGDATA: /pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    networks:
      - cff-stack
    volumes:
      - pgdata:/pgdata
      - wiyby:/wiyby
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: postgres -c max_wal_size=2048 # set max_wal_size to prevent warnings when restoring db

networks:
  cff-stack:

volumes: 
  pgdata:
  wiyby:
