# Template for running data-load jobs on the docker DB without requiring local
# psql installation.
#
# Example:
# docker compose -f docker-compose.yml -f docker-compose-thresholds.yml run \
#   flood-db sh -c "cd /data-load && ./<copy-script>"

services:
  flood-db:
    environment:
     LFW_DATA_DB_CONNECTION: postgres://u_flood:secret@flood-db:5432/flooddev
    volumes:
      # Add the mounts needed for the specific data-load job.
      # - ../../../../../data-load/<job>/<file>.csv:/data-load/<file>.csv
      # - ../../../../../data-load/<job>/<copy-script>:/data-load/<copy-script>
