services:
  liquibase:
    build:
      context: .
      dockerfile: Dockerfile.liquibase
    depends_on:
      flood-db:
        condition: service_healthy
    volumes:
      - ../..:/liquibase/u_flood
      - ./wait-for-postgis.sh:/wait-for-postgis.sh:rw
    networks:
      - cff-internal
    entrypoint: /bin/bash
    command: >
      -c "
        /wait-for-postgis.sh && \
        liquibase --username=u_flood --password=secret --defaultSchemaName=u_flood --liquibaseSchemaName=u_flood --driver=org.postgresql.Driver --changeLogFile=db.changelog-master.xml --contexts=local --url=jdbc:postgresql://flood-db:5432/flooddev --searchPath=/liquibase/u_flood/changelog,/liquibase/u_flood update
      "
