version: "3.6"
name: cff

services:
  flood-db:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    shm_size: 1g
    environment:
      PGDATA: /pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - pgdata:/pgdata
      - wiyby:/wiyby
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: postgres -c max_wal_size=2048 # set max_wal_size to prevent warnings when restoring db

volumes: 
  pgdata:
  wiyby:
